### PR TITLE
Avoid test directory collisions

### LINKED ISSUE #32: Test directory naming simplification introduces collisions
I think the new directory naming convention introduced in #27 is a win, but we need an additional component in the name. Many (all?) of the tests are run in parallel, and the `CoreSimpleTests` and `CoreISATests` end up sharing the same directory for the `rv32ui-p-simple` test, and thus colliding (especially on heavily loaded systems):
```
[info] CoreSimpleTests:
[info] mini.CoreSimpleTests *** ABORTED ***
[info]   java.io.IOException: Cannot run program "./VCoreTester" (in directory "test_run_dir/CoreTester_rv32ui-p-simple"): error=26, Text file busy
```
Jenkins testing shows collisions generating the simulation source files:
```
In file included from VTileTester__ALLcls.cpp:3:0:
VTileTester.cpp:11516:1: error: expected ‘}’ at end of input
 }
 ^
VTileTester.cpp:11516:1: error: expected unqualified-id at end of input
VTileTester.cpp:11516:1: error: expected ‘}’ at end of input
VTileTester.cpp:11516:1: error: expected unqualified-id at end of input
```

### PR DESCRIPTION
**Pull request by ucbjrl**
Add the TestType.namePrefix to the test name to produce the nameHint.
Fixes #32

### CODE REVIEW

**Comment by ucbjrl** [comment]
I don't know whether it would be better to use the test namePrefix for an actual directory, so all the subtests are in the same directory. It seemed that that change would be more intrusive, but I suppose you could split the nameHint on '/' and create the needed directory path.

Left as an exercise for the user.

I'll commit this as is just to get Jenkins tests running again.
