### ISSUE TITLE
Test directory naming simplification introduces collisions

### ISSUE THREAD

**Issue by ucbjrl** [ucb-bar/riscv-mini#32]
I think the new directory naming convention introduced in #27 is a win, but we need an additional component in the name. Many (all?) of the tests are run in parallel, and the `CoreSimpleTests` and `CoreISATests` end up sharing the same directory for the `rv32ui-p-simple` test, and thus colliding (especially on heavily loaded systems):
```
[info] CoreSimpleTests:
[info] mini.CoreSimpleTests *** ABORTED ***
[info]   java.io.IOException: Cannot run program "./VCoreTester" (in directory "test_run_dir/CoreTester_rv32ui-p-simple"): error=26, Text file busy
```
Jenkins testing shows collisions generating the simulation source files:
```
In file included from VTileTester__ALLcls.cpp:3:0:
VTileTester.cpp:11516:1: error: expected ‘}’ at end of input
 }
 ^
VTileTester.cpp:11516:1: error: expected unqualified-id at end of input
VTileTester.cpp:11516:1: error: expected ‘}’ at end of input
VTileTester.cpp:11516:1: error: expected unqualified-id at end of input
```

**Comment by ucbjrl** [comment]
Closed by #33
